services:
  postgres:
    container_name: postgres_go_social-api
    image: postgres:16.4
    environment:
      POSTGRES_DB: social-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"

  redis:
    container_name: redis_go_social-api
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  redis-commander:
    container_name: redis-commander_go_social-api
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
